### ISSUE TITLE
Having just one mark throws off zoom

### ISSUE THREAD

**Issue by AckerApple** [AckerApple/agm-overlays#1]
Having just one custom overlay always causes super zoomed in because .fitBounds is being called.

Possible solutions:
- Try to read set zoom of agm
- Dont call fitBounds() when only one overlay (sounds promising, may need to comunicate lat lng to map for focus only)

**Comment by MaxSwank** [comment]
Experiencing this issue.  Possible examples for how to implement either of these solutions?

**Comment by AckerApple** [comment]
It’s going to take me releasing a fix today. That’s all.

**Comment by AckerApple** [comment]
Fixed!

Please install version 1.0.4 and test

And report back if you would please of what you see
