### ISSUE TITLE
Work with Angular universal

### ISSUE THREAD

**Issue by Akumuliation** [AckerApple/agm-overlays#10]
Please add support Angular universal.
Now i have error "ERROR ReferenceError: window is not defined"
)

**Comment by AckerApple** [comment]
I searched all code. I do NOT use any `window` references.

Maybe agm-core does?

**Comment by AckerApple** [comment]
All my code for the overlay work occurs here and it has no window references: https://github.com/AckerApple/agm-overlays/blob/master/src/AgmOverlay.component.ts

**Comment by AckerApple** [comment]
This package, agm-overlays, also offers marker-clustering and I think the package we depend on for clutering maybe the one that has the window reference.

This package: [js-marker-clusterer](https://www.npmjs.com/package/js-marker-clusterer)

**Comment by AckerApple** [comment]
Fare warning, I will close this issue next time I review this packages issues
