### ISSUE TITLE
Feature request: Overlays in street view

### ISSUE THREAD

**Issue by IsaacSomething** [AckerApple/agm-overlays#17]
Just wondering if maybe this is something that agm-overlays is looking to do in the future, would be a nice feature, or maybe it can already be done ( and i dont know what im doing )

**Comment by AckerApple** [comment]
That’s something I’ve never done nor seen done. It’s not something that I think any of us supporting this package have a need for so chances of additional support for it are very unlikely

**Comment by IsaacSomething** [comment]
Ok cool, I was looking for something like this http://projects.teammaps.com/projects/streetviewoverlay/streetviewoverlay.htm

rad module btw .. very easy to use and setup
