### ISSUE TITLE
[Error - readme] Bounds

### ISSUE THREAD

**Issue by rbalet** [AckerApple/agm-overlays#20]
Incorrect bounds attribute into the readme

(Not sure about that) The bounds attribute should be in the agm-overlay instead of the agm-map

**Comment by AckerApple** [comment]
Not sure to what you are referencing. Could you help further and elaborate.

Thank you kindly for being helpful

**Comment by rbalet** [comment]
For sure, sorry for the unclarity.

Like the example you linked, this bounds should be within the agm-overlay 
![image](https://user-images.githubusercontent.com/44493964/50072654-4c862680-01d6-11e9-8118-9834f4a8f1bc.png)

(On the left the code I found in your readme, on the right, how it should be)

I take for example the code found into [agm-overlays/example/src/app.template.ts](url)
![image](https://user-images.githubusercontent.com/44493964/50072707-7fc8b580-01d6-11e9-85e2-6a4d635bc510.png)

> I'm not 100% sure about what I say, but using the bounds attribute within the agm-map led me to errors

**Comment by AckerApple** [comment]
I much appreciate you bringing this to my attention. I have adjusted the README.md but have NOT republished to npm yet. With the next release, the README.md will be updated everywhere and not just Github.

Special request, I like to remember those I work with plus for many other great reasons, please consider my request of you to have legit Github icon of yourself.

Be well. Feel free to contact me about this or any of my packages or if you happen to play a really great pinball machine. I love pinball

![unadjustednonraw_thumb_dca](https://user-images.githubusercontent.com/7964429/50101325-78aea100-01f0-11e9-9c8c-4c9a6ad9fe5e.jpg)

**Comment by rbalet** [comment]
Well, I gonna do that ;)

I then close this issue, thanks a lot for this plugin.
