### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by matejferenc** [AckerApple/agm-overlays#21]
Could the documentation be enhanced to actually say what this package does?
I want to create overlays on top of agm-map (like this: https://developers.google.com/maps/documentation/javascript/examples/overlay-simple)
However I have an impression that your library does actually do something else.
Thanks.

**Comment by AckerApple** [comment]
I’m a big fucking ass hole like yourself. Nice to meet your ugly attitude. Now fuck off because the meeting of assholes to talk about shit bags, isn’t about to happen here.

**Comment by AckerApple** [comment]
Sorry. You caught me at a horrible moment in life. Too much on my plate and being bothered from too many directions.

Best of luck to you
