### ISSUE TITLE
same coords

### ISSUE THREAD

**Issue by newprogrammer1991** [AckerApple/agm-overlays#28]
Hi! Please help with the same coords, I can't click and how to avoid it becouse some times we have the same coords 
![image](https://user-images.githubusercontent.com/25803072/56359058-2d7dbc80-61e9-11e9-94e4-de60ba5941fe.png)

**Comment by AckerApple** [comment]
You're giving me little to no details. I very much doubt there is any issue.

Your name, newprogrammer, says it all.

Sorry, I'm not here to be a tutor

**Comment by newprogrammer1991** [comment]
What about this package https://www.npmjs.com/package/agm-oms ?

**Comment by newprogrammer1991** [comment]
> You're giving me little to no details. I very much doubt there is any issue.
> 
> Your name, newprogrammer, says it all.
> 
> Sorry, I'm not here to be a tutor

What about this package https://www.npmjs.com/package/agm-oms ?

**Comment by AckerApple** [comment]
I've never seen that package before.

Hey listen, if you're going to leave these one line comments with no details: You can piss off now, please. I often choose to be rude to push annoyances away. Sorry to be rude, I can't be distracted by cocktail talk.

You need to elaborate more but honestly I think you should just close this issue and move on from me

**Comment by havo07** [comment]
Hi @newprogrammer1991, you use js-marker-clusterer?, if is yes, my recomendation is use prop  "minimumClusterSize" and seting in 3, if you use agm-oms read documentation, this nmp not generate you error, regards.

**Comment by newprogrammer1991** [comment]
> Hi @newprogrammer1991, you use js-marker-clusterer?, if is yes, my recomendation is use prop "minimumClusterSize" and seting in 3, if you use agm-oms read documentation, this nmp not generate you error, regards.

Thank you! Your answer is better and clearer than the author of this package! Thanks a lot!

**Comment by AckerApple** [comment]
YUP! Cause you give shitty details and pray for an answer.
