### ISSUE TITLE
markerClick not work

### ISSUE THREAD

**Issue by havo07** [AckerApple/agm-overlays#29]
Hi,  I'm implementing your npm but when I click on the overlay it gives me the following error, I thought it had to do with "agm-marker-cluster" but it's not like that, to get it I have to perform the click and a small drag

Error is:
_Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted._

My code html:
![code](https://user-images.githubusercontent.com/6580252/57716795-63269180-763f-11e9-8d10-9095bb4089e4.PNG)

Result before click:
![result_1](https://user-images.githubusercontent.com/6580252/57716801-66218200-763f-11e9-8297-5779661240c1.PNG)

**Comment by AckerApple** [comment]
This package implements a js library called "js-marker-clusterer"

It maybe your issue is coming from there. This package boils down to one component and then it relies on js-marker-clusterer to do the rest.

Link to really only file used in this package:
https://github.com/AckerApple/agm-overlays/blob/master/src/AgmOverlay.component.ts

Link to js-marker-cluster package:
https://www.npmjs.com/package/js-marker-clusterer

**Comment by havo07** [comment]
Remove the agm-marker-cluster code as a test but I can not get an answer, just click and a small drag

**Comment by AckerApple** [comment]
I'm not sure what your last comment is saying?

**Comment by havo07** [comment]
> I'm not sure what your last comment is saying?

Sorry.

It works when I do 2 clicks but it expands on the map, when I click and drag

**Comment by AckerApple** [comment]
I think you are just reciting the issue you've already explained.

I went to the demo page for this package on my iPhone. I only had to tap once on a cluster and it zoomed in and separated the cluster into individual markers.

As far as I can tell everything is working as expected.

Demo page:
https://ackerapple.github.io/agm-overlays/

Demo page source code:
https://github.com/AckerApple/agm-overlays/tree/master/example/src

**Comment by havo07** [comment]
The problem is not the cluster, the problem is related to the overlay, the MarkerClick function is not entered, it seems that the MapClick event is by default and not the overlay

I put a video I hope you understand me
[https://vimeo.com/user98515389/review/336169451/e9af3dc45a](url)

**Comment by AckerApple** [comment]
The video link does not seem to work.

If I understand you, you want to add a click action to the cluster?


Hey listen, let me save you a lot of time ====> I lost my job just as of Friday. I have no time to investigate or make fixes. You will be on your own. I can accept pull requests at best.

**Comment by havo07** [comment]
You do not understand me, the MapClick event of agm-map is above, for the MarkerClick agm-overlay event, is there any way to put the agm-overlar over the Click event of the map?

**Comment by havo07** [comment]
> The video link does not seem to work.
> 
> If I understand you, you want to add a click action to the cluster?
> 
> Hey listen, let me save you a lot of time ====> I lost my job just as of Friday. I have no time to investigate or make fixes. You will be on your own. I can accept pull requests at best.

Understand, thank you...

**Comment by havo07** [comment]
> The video link does not seem to work.
> 
> If I understand you, you want to add a click action to the cluster?
> 
> Hey listen, let me save you a lot of time ====> I lost my job just as of Friday. I have no time to investigate or make fixes. You will be on your own. I can accept pull requests at best.

I detect a problem with set event "Click" in overlay and previus set event to "Click" in map, the sequence of execute in event is overlay and next steep is map, the fix is modified the file AgmOverlay.component.js, i would like to allow you to collaborate with your repository with this solution.

**Comment by AckerApple** [comment]
Yes I’d accept a pull request of yours. Let me know or look up if you need help on the subject of pull requests. Just fork my code, make the fix, and request a pull request. I’ll even test it.

This package has just a few branches. Be sure to be on the one with the “src” folder and use the scripts in package.json to build and watch

**Comment by havo07** [comment]
Error, remote Permission to summit

**Comment by AckerApple** [comment]
I went to your repositories and you didn't even fork the code for this library.

Please learn how to use the github public system of forking code and then issuing a pull request.

When you do this right, you will have a "fork" of my code here in your repositories: https://github.com/havo07?tab=repositories

Here is the top result for "my first pull request" on youtube:
https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by AckerApple** [comment]
I published version 1.4.0

If this does not work, try a pull request again but only change what needs to be changed
