### ISSUE TITLE
Load Images

### ISSUE THREAD

**Issue by uttamchaturvedi9** [AckerApple/agm-overlays#48]
I have one requirement to show/hide images on google map using agm something as shown below. I think there is some utility is available with AGM, however i am not aware of it.Below is my code to load map and on handleOnTilesLoaded() method I would like to add some code to load images.
<agm-map [zoom]="5" [latitude]="lat" [longitude]="lng" (mapReady)="onMapReady($event)"
    (mapClick)="mapClick($event)" (mapReady)="mapReady($event)"(tilesLoaded)="handleOnTilesLoaded()">  
 </agm-map>

![2020-11-03_19h21_17](https://user-images.githubusercontent.com/29146996/98125466-cef45e00-1eb4-11eb-9b0b-7dbfcf9a2564.png)

**Comment by AckerApple** [comment]
And the award for least amount of details in an issue description goes to...

**Comment by uttamchaturvedi9** [comment]
Sorry for not providing complete details. I hope this must be clear now

**Comment by AckerApple** [comment]
Just use an ngIf on your agm-overlay to turn on off at will.

Put an img tag inside your agm-overlay and use ngIf to turn on off

**Comment by uttamchaturvedi9** [comment]
Thanks Looks good

**Comment by AckerApple** [comment]
Close this issue. This is such a small matter you could have solved yourself. First no details then too much details. I mean an image tag and some ngif, you coulda come up with that.

**Comment by uttamchaturvedi9** [comment]
fixed
