### ISSUE TITLE
Fails in Angular 6 library at least

### ISSUE THREAD

**Issue by mockuniverse** [AckerApple/agm-overlays#6]
Your package isn't found when including in Angular 6 library.  Maybe incompatible with NG6? In any event it doesn't work. 

BTW, this not part of the **agm** product so why use the "agm" prefix?  A unique scope would be better, like` @acker/overlay` and acker-overlay as the selector.  Also, why does your example use **--save-dev** rather than --save? 

This is from your example. Did you actually test this as an npm module include? 

`import { AgmOverlays } from "../../src"`

**Comment by AckerApple** [comment]
I think you should go back to watching video games on Twitch.

You and this issue report can sit and think of a better way to communicate to maintainers of free code

**Comment by AckerApple** [comment]
This package works with Angular 6

It's just you that sucks, go back to watching games on Twitch


Everything else you said is crap and your github account is crap. Go away

**Comment by AckerApple** [comment]
And if you knew your face from an ass in the wall, you'd read the damn documentation on how to import this package: https://github.com/AckerApple/agm-overlays#import

This package is in use by many....... "Did you actually test this as an npm module include?", go eat like 12 donkey dicks.... Of course I tested this shit and its in use by many who say "this is terrific, i dont know why agm didnt include this by default"

**Comment by AckerApple** [comment]
At the end of this rat race, even if you win, you'll still be a rat

**Comment by tobiasgruber-at** [comment]
Can only agree with you @AckerApple, you are great for providing this package to our community!:)

**Comment by AckerApple** [comment]
Thank you extra kindly @TobiasGruberAT. I can be a bit mouthy and even overly defensive and so it’s still great to get support like your comment because after all we really did spend a lot of time on this package and I have risen to the demands of the issue reports and pull requests.

It so sucks to provide free work and then be shat on. You have balanced me out @TobiasGruberAT and I again appreciate your short comment so very much

**Comment by tobiasgruber-at** [comment]
Glad to hear that:) Your package is really practical and comfortable to use and it's helping a lot of developers, unfortunately most people tend to see the small bugs and errors instead of the working part and the effort behind it!
Oh and I think you package name is perfect:)
